version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djgallery
      - POSTGRES_USER=djgallery
      - POSTGRES_PASSWORD=djgpassoneone
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=djgallery
      - POSTGRES_USER=djgallery
      - POSTGRES_PASSWORD=djgpassoneone
    depends_on:
      - db
volumes:
  postgres_db:
